/** @type {import('tailwindcss').Config} */
// Paleta y tipografía tomadas del design system entregado por el equipo de diseño
// (stitch_tornotech_cnc_lms_simulator/tornotech_precision_system/DESIGN.md).
// "Industrial Minimalism": dark-mode first, alta densidad de datos, bajo brillo para planta.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#00344b",
        outline: "#87929b",
        "primary-fixed": "#c6e7ff",
        "secondary-container": "#ed9000",
        "on-surface": "#d6e4f9",
        "primary-container": "#00a8e8",
        "inverse-surface": "#d6e4f9",
        "surface-dim": "#061423",
        error: "#ffb4ab",
        "surface-bright": "#2d3a4a",
        "on-secondary-container": "#583300",
        "on-error": "#690005",
        primary: "#83cfff",
        "on-tertiary": "#2f312e",
        "inverse-primary": "#00658d",
        "on-tertiary-fixed-variant": "#454745",
        "surface-tint": "#83cfff",
        "secondary-fixed": "#ffdcbc",
        "on-primary-container": "#003952",
        "secondary-fixed-dim": "#ffb86b",
        "on-tertiary-fixed": "#1a1c1a",
        "inverse-on-surface": "#243141",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#e2e3df",
        "outline-variant": "#3e4850",
        "on-surface-variant": "#bdc8d1",
        background: "#061423",
        surface: "#061423",
        "on-secondary": "#492900",
        "tertiary-fixed-dim": "#c6c7c3",
        "surface-variant": "#283646",
        "on-primary-fixed-variant": "#004c6b",
        "tertiary-container": "#9c9e9a",
        "on-secondary-fixed-variant": "#683d00",
        "primary-fixed-dim": "#83cfff",
        "error-container": "#93000a",
        "on-primary-fixed": "#001e2d",
        "surface-container-lowest": "#020f1e",
        "surface-container-highest": "#283646",
        secondary: "#ffb86b",
        "surface-container-high": "#1e2b3b",
        "surface-container-low": "#0f1c2c",
        "on-tertiary-container": "#333533",
        tertiary: "#c6c7c3",
        "on-secondary-fixed": "#2c1700",
        "surface-container": "#132030",
        "on-background": "#d6e4f9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        margin: "24px",
        unit: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
